apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-network-monitor
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-network-monitor
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-network-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-network-monitor
subjects:
- kind: ServiceAccount
  name: pod-network-monitor
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pod-network-monitor
  namespace: kube-system
  labels:
    app: pod-network-monitor
spec:
  selector:
    matchLabels:
      app: pod-network-monitor
  template:
    metadata:
      labels:
        app: pod-network-monitor
    spec:
      serviceAccountName: pod-network-monitor
      hostNetwork: true
      hostPID: true
      containers:
      - name: monitor
        image: pod-network-monitor:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
            - NET_ADMIN
            - BPF
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_SELECTOR
          value: "monitor=external"  # Change this to your label selector
        - name: BLOCK_EXTERNAL
          value: "false"  # Set to "true" to block external traffic
        - name: INTERNAL_CIDRS
          value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"  # Adjust for your cluster
        volumeMounts:
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: proc
          mountPath: /host/proc
          readOnly: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: proc
        hostPath:
          path: /proc
      tolerations:
      - effect: NoSchedule
        operator: Exists
